title: Chopngjian Wang's Homepage
page-top-title: Chongjian Wang
top-section-bg-text: 3D Vision,Deep learning,Machine Learning
home-subtitle: Chongjian Wang&ensp;|&ensp;王崇简
copyright-text: '&copy; Chongjian Wang 2023-2026. All Rights Reserved.'
